[build]
  command = "pnpm build"
  publish = "dist/pwa"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "https://bowenferry.ca/Production/:splat"
  status = 200
  force = true

[context.production]
  environment = { PRODUCTION = "true" }
  [[context.production.redirects]]
    from = "/webcam/*"
    to = "https://storage.googleapis.com/bowen-ferry.firebasestorage.app/webcams/:splat"
    status = 200

[context.branch-deploy]
  [[context.branch-deploy.redirects]]
    from = "/webcam/*"
    to = "https://storage.googleapis.com/bowen-ferry-staging.firebasestorage.app/webcams/:splat"
    status = 200

[context.deploy-preview]
  [[context.deploy-preview.redirects]]
    from = "/webcam/*"
    to = "https://storage.googleapis.com/bowen-ferry-staging.firebasestorage.app/webcams/:splat"
    status = 200
