<template>
  <q-page>
    <!-- Static training-review report generated by scripts/train-lineup-classifier.mjs
         into public/classifier-results/ — served outside the SPA, embedded here so
         the app chrome stays available. -->
    <iframe
      src="/classifier-results/"
      title="Lineup classifier training results"
      style="width: 100%; height: calc(100vh - 50px); border: none"
    />
  </q-page>
</template>
