<template>
  <q-page>
    <!-- Static training-review report generated by the trainers into
         public/classifier-results/. That directory is gitignored (~75 MB of
         regenerated pages + thumbnails), so the deployed app embeds the copy
         published to Cloud Storage (npm run deploy:classifier-results), while
         a dev server embeds the local files — which is what you want right
         after a training run. -->
    <iframe
      :src="reportUrl"
      title="Lineup classifier training results"
      style="width: 100%; height: calc(100vh - 50px); border: none"
    />
  </q-page>
</template>

<script setup>
import { storageBucket } from 'src/boot/firebase'

const isDev = process.env.DEV === true || process.env.DEV === 'true'
const reportUrl = isDev
  ? '/classifier-results/'
  : `https://storage.googleapis.com/${storageBucket}/classifier-results/index.html`
</script>
