name: Secrets Scan

on:
  push:
    branches:
      - main
      - production
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog
        uses: trufflesec/trufflehog-action@main
        with:
          source: '.'
          base: ${{ github.event.repository.default_branch }}
          extra_args: '--json --entropy'
        continue-on-error: false